### PR TITLE
proposed solution to culling species after x generations

### PR DESCRIPTION
**Pull request by jrraymond**

### CODE REVIEW

**Comment by mdietz94** [comment]
So the 1 thing I think, is that stagnation is not a Genome level thing, it's a Species level thing.  All the other changes are good though, but we need to make children inherit their parent's stagnation + 1, and only reset it to 0 if their fitness improves after evaluation

**Comment by jrraymond** [comment]
I aborted because I realized that I was doing stagnation on genomes which doesn't make any sense

**Comment by mdietz94** [comment]
Yeah but the other stuff was good... like the fix for the genetic difference thing.  Cherry-pick that one at least

**Comment by mdietz94** [comment]
also you could store it in genomes, because we don't keep species lists, we generate that as we go

**Comment by mdietz94** [comment]
Oh I see you did leave that, but why did you flip the arguments on adjustedFitness?

**Pull request merged**
